name: jinro_web
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.0-dev.7
  state_notifier: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.14.0+1

flutter:
  uses-material-design: true
